import { Item } from './types';

export const MOCK_ITEMS: Item[] = [
  {
    id: '8',
    title: 'brainrots Secret Chimnino radioactif',
    price: 15.00,
    currency: '€',
    brand: 'Winter Update',
    size: 'Unique',
    condition: 'Neuf avec étiquette',
    imageUrl: 'https://i.ibb.co/JWxPs4jY/Capture-d-cran-2025-12-14-181401.png',
    vintedUrl: 'https://www.vinted.fr/member/179294248-spideyaxel',
    sellerName: 'spideyaxel',
    sellerRating: 0,
    sellerReviewCount: 0,
    description: 'Un des 4 nouveaux brainrots de noël de la dernière mise a jour \nVous pouvez venir base vide pour le récupérer',
    likes: 666,
    isBrainrot: true,
    aura: 500000000, // 500M
    rarity: 'secret',
  },
  {
    id: '10',
    title: 'brainrots Secret Gyftini Spyderini mutation flamme',
    price: 2.00,
    currency: '€',
    brand: 'Winter Update',
    size: 'Unique',
    condition: 'Neuf avec étiquette',
    imageUrl: 'https://i.ibb.co/8nMcbK6k/Capture-d-cran-2025-12-14-192315.png',
    vintedUrl: 'https://www.vinted.fr/member/179294248-spideyaxel',
    sellerName: 'spideyaxel',
    sellerRating: 0,
    sellerReviewCount: 0,
    description: 'Un des 16 nouveaux brainrots de noël de la dernière mise a jour \nVous pouvez venir base vide pour le récupérer',
    likes: 88,
    isBrainrot: true,
    aura: 5900000, // 5.9 M
    rarity: 'secret',
  },
  {
    id: '9',
    title: 'brainrots Secret Naughty Naughty Diamant',
    price: 2.00,
    currency: '€',
    brand: 'Winter Update',
    size: 'Unique',
    condition: 'Neuf avec étiquette',
    imageUrl: 'https://i.ibb.co/twcwk0tp/Capture-d-cran-2025-12-14-192302.png',
    vintedUrl: 'https://www.vinted.fr/member/179294248-spideyaxel',
    sellerName: 'spideyaxel',
    sellerRating: 0,
    sellerReviewCount: 0,
    description: 'Un des 16 nouveaux brainrots de noël de la dernière mise a jour \nVous pouvez venir base vide pour le récupérer',
    likes: 42,
    isBrainrot: true,
    aura: 4500000, // 4.5M
    rarity: 'secret',
  },
  {
    id: '13',
    title: 'brainrot god Chrismasmamat diamand avec mutation tacos Nyan Snowy et bresil',
    price: 2.00,
    currency: '€',
    brand: 'Winter Update',
    size: 'Unique',
    condition: 'Neuf avec étiquette',
    imageUrl: 'https://i.ibb.co/jvdvLNy0/Capture-d-cran-2025-12-14-192400.png',
    vintedUrl: 'https://www.vinted.fr/member/179294248-spideyaxel',
    sellerName: 'spideyaxel',
    sellerRating: 0,
    sellerReviewCount: 0,
    description: 'Un des 16 nouveaux brainrots de noël de la dernière mise a jour \nVous pouvez venir base vide pour le récupérer',
    likes: 55,
    isBrainrot: true,
    aura: 4300000, // 4.3 M
    rarity: 'god',
  },
  {
    id: '12',
    title: 'Brainrot God Cocoa Assassino',
    price: 1.50,
    currency: '€',
    brand: 'Winter Update',
    size: 'Unique',
    condition: 'Neuf avec étiquette',
    imageUrl: 'https://i.ibb.co/GvXpmkkj/Capture-d-cran-2025-12-14-192345.png',
    vintedUrl: 'https://www.vinted.fr/member/179294248-spideyaxel',
    sellerName: 'spideyaxel',
    sellerRating: 0,
    sellerReviewCount: 0,
    description: 'Un des 16 nouveaux brainrots de noël de la dernière mise a jour \nVous pouvez venir base vide pour le récupérer',
    likes: 77,
    isBrainrot: true,
    aura: 1300000, // 1.3 M
    rarity: 'god',
  },
  {
    id: '11',
    title: 'brainrot secret please my present',
    price: 1.50,
    currency: '€',
    brand: 'Winter Update',
    size: 'Unique',
    condition: 'Neuf avec étiquette',
    imageUrl: 'https://i.ibb.co/WpyM6t41/Capture-d-cran-2025-12-14-192327.png',
    vintedUrl: 'https://www.vinted.fr/member/179294248-spideyaxel',
    sellerName: 'spideyaxel',
    sellerRating: 0,
    sellerReviewCount: 0,
    description: 'Un des 16 nouveaux brainrots de noël de la dernière mise a jour \nVous pouvez venir base vide pour le récupérer',
    likes: 33,
    isBrainrot: true,
    aura: 1300000, // 1.3 M
    rarity: 'secret',
  },
];